### ISSUE TITLE
Initial set tab="0" not working as expected

### ISSUE THREAD

**Issue by OpenNoob** [saravmajestic/ionic#13]
Hi,

Great work!

I have an issue with::

<tab-slide-box tabs-position="bottom" tab="0">

It points to first icon but it doesn't add the "active" class. Anyone else can replicate?

Thanks, Great work again!

**Comment by saravmajestic** [comment]
Hi, I have created a demo with tab as 0. Please check: http://ionic-sarav.rhcloud.com/ionic/tabbedSlideBox/slidingContent.html#/
