### ISSUE TITLE
Position of tab reset with bar event [SOLVED]

### ISSUE THREAD

**Issue by ghost** [saravmajestic/ionic#28]
Hi,

I have a toggle in my app.
If I choose the third element (for example) and then I click on my toggle, the tab returns in initial position...

Do you know this issue ?

**Comment by saravmajestic** [comment]
I have not used toggle inside this component. Can you create a plunkr?

**Comment by ghost** [comment]
Hello,

Here the plunkr : http://plnkr.co/edit/7GmvbCZ6CTTXkhtYQFvx?p=preview

Reduce the preview's width on the right, go to the last tab and click on the toggle to see the issue.

**Comment by ghost** [comment]
Hello,

Any action in the header bar reset the position of the scroll tabs bar.
So set the "no-tap-scroll" property of ion-nav-bar/ion-header-bar to true solved the problem.

Issue resolved.
