### ISSUE TITLE
Slide content issue

### ISSUE THREAD

**Issue by marcoiacobelli** [saravmajestic/ionic#29]
Hi,
tnx for this amazing library!
I have a problem, the content of the slide (a list of items) it's cut! Any ideas on how to fix it?
thxs

link for error video: http://www.itmakers.it/video-error/rightmeal.mov

**Comment by saravmajestic** [comment]
I think its because of "bottom" positioning. Can you try adding some padding at bottom? If it is still not working, can you create a plunkr?

**Comment by marcoiacobelli** [comment]
hi it's my problem, with scrollable template work like a charm.
:+1:
