### ISSUE TITLE
While scrolling the content after some scroll the current tab was out of view ?

### ISSUE THREAD

**Issue by Gopinath7007** [saravmajestic/ionic#49]
Hi While Scrolling the content the content slide is changing but the current tab is in out of view how to solve this ?

**Comment by Gopinath7007** [comment]
I have Solved this issue it is ionic issue ... Just copy go to the link(http://code.ionicframework.com/1.0.0-rc.4/js/ionic.bundle.min.js) and copy entire file save it to www/js foler and replace instead of ionic.bundle.min.js

**Comment by anjali14garg** [comment]
Gopinath7007  this is not working
