### ISSUE TITLE
Scrollable content

### ISSUE THREAD

**Issue by dackyD** [saravmajestic/ionic#5]
Hi, 

Thank you for this great component. I am using and recommending this by the way. It would be great if the scrollable tabs support scrollable content as well. If I understood completely in your examples, you placed the slideboxes inside the ion-content which scroll was set to false. It would be nice if it is the other way around like the ion-content inside the slidebox. Just like the scrollable tabs in android http://developer.android.com/design/building-blocks/tabs.html

Hope you can include this feature in your next version. Thanks once again.

**Comment by saravmajestic** [comment]
Hi @naveenkarippai1 , do you see any problem in using http://ionic-sarav.rhcloud.com/ionic/tabbedSlideBox/slidingTabs.html#/ which has scrollable tabs. I have updated the code to use beta 14 as well. Or did you mean scrollable content when selecting the tabs?

**Comment by kushalarora92** [comment]
Hey. Please tell how to make the content scrollable in this??

**Comment by saravmajestic** [comment]
Hey. Inside ```ion-slide```, you have to use ```ion-scroll style="height:100%"```. Please try it out and let me know

**Comment by kushalarora92** [comment]
Hey please see the below code.
Cant scroll below a certain list items... please see first two slides.
Regards
Kushal


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1,
user-scalable=no, width=device-width">
    <title>Tabbed Slide box</title>

    
    <link href="http://code.ionicframework.com/1.0.0-beta.14/css/ionic.css"
rel="stylesheet">

    
    <link href="tabSlideBox.css" rel="stylesheet">

    
    <script src="
http://code.ionicframework.com/1.0.0-beta.14/js/ionic.bundle.js"></script>
 <script src="tabSlideBox.js"></script>
 
    <script>
    var app = angular.module('slidebox', ['ionic', 'tabSlideBox'])
.run(['$q', '$http', '$rootScope', '$location', '$window', '$timeout',
function($q, $http, $rootScope, $location, $window, $timeout){

        $rootScope.$on("$locationChangeStart", function(event, next,
current){
            $rootScope.error = null;
            console.log("Route change!!!", $location.path());
            var path = $location.path();


            console.log("App Loaded!!!");
        });
    }
    ]);
 app.config(function($stateProvider, $urlRouterProvider) {
$stateProvider.state('index', {
url : '/',
templateUrl : 'index.html',
controller : 'IndexCtrl'
});
 $urlRouterProvider.otherwise("/");
});
        app.controller("IndexCtrl", ['$rootScope', "$scope",
"$stateParams", "$q", "$location", "$window", '$timeout',
function($rootScope, $scope, $stateParams, $q, $location, $window,
$timeout){
 $scope.tabs = [
{"text" : "Home"},
{"text" : "Games"},
{"text" : "Mail"},
{"text" : "Car"},
{"text" : "Profile"},
{"text" : "Favourites"},
{"text" : "Chats"},
{"text" : "Settings"},
{"text" : "Photos"},
{"text" : "Pets"}
];
$scope.onSlideMove = function(data){
alert("You have selected " + data.index + " tab");
};
        }
        ]);
    </script>

<style>
.slider-slide h3{
color:#fff;
margin-top:10px;
}
.scroll{
height:100%;
}
 .tabbed-slidebox .tsb-icons:after{
display:none;
}
</style>
  </head>

  <body ng-app="slidebox" animation="slide-left-right-ios7">

    <ion-nav-bar class="nav-title-slide-ios7 bar-positive">
        <ion-nav-back-button class="button-icon ion-arrow-left-c">
        </ion-nav-back-button>
    </ion-nav-bar>

    <ion-nav-view ng-controller="IndexCtrl"></ion-nav-view>
 <script id="index.html" type="text/ng-template">
      <ion-view title="Scrollable Tabbed Slide box">
        <ion-content scroll="false">
          <tab-slide-box>
     <div class="tsb-icons">
     <div class="tsb-ic-wrp">
<ion-scroll direction="x" class="tsb-hscroll">
<a href="javascript:;" class="{{tab.icon}}" ng-repeat="tab in tabs"
on-finish-render="test()">{{tab.text}}</a>
</ion-scroll>
</div>
     </div>
        <ion-slide-box show-pager="false"
on-slide-changed="slideHasChanged($index)">
            <ion-slide>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>
                <h3>Home content</h3>

            </ion-slide>
            <ion-slide>
                <ion-list>
                <ion-scroll style="height:100%">
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>
                 <ion-item>check</ion-item>

                </ion-item>
            </ion-slide>
            <ion-slide>
                <h3>Mail content</h3>
            </ion-slide>
<ion-slide>
                <h3>Car content</h3>
            </ion-slide>
            <ion-slide>
                <h3>Profile content</h3>
            </ion-slide>
            <ion-slide>
                <h3>Favourites content</h3>
            </ion-slide>
<ion-slide>
                <h3>Chats content</h3>
            </ion-slide>
<ion-slide>
                <h3>Settings content</h3>
            </ion-slide>
<ion-slide>
                <h3>Photos content</h3>
            </ion-slide>
<ion-slide>
                <h3>Pets content</h3>
            </ion-slide>
        </ion-slide-box>
          </tab-slide-box>
        </ion-content>
      </ion-view>
    </script>
  </body>
</html>


On Thu, Feb 5, 2015 at 4:46 PM, saravmajestic <notifications@github.com>
wrote:

> Hey. Inside ion-slide, you have to use ion-scroll style="height:100%".
> Please try it out and let me know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saravmajestic/ionic/issues/5#issuecomment-73030647>.
>



-- 
Regards
*Kushal Arora*
+91-9711-979940
kushalarora92@gmail.com

**Comment by saravmajestic** [comment]
Hope you might have solved it by now. I have also added a demo for this: http://ionic-sarav.rhcloud.com/ionic/tabbedSlideBox/slidingContent.html#/

**Comment by emiidee** [comment]
The demo is not working. On the home, it doesn't reach the bottom of the content. Help?

**Comment by emiidee** [comment]
As a temporary fix, I added a style "bottom: 110px" to the ion-content of each slide

**Comment by saravmajestic** [comment]
Yes. bottom property has to be added for making the content visible.

**Comment by usmanmirza** [comment]
Hi Sarav,
Great work with slider,
I have an issue with ui bootstrap that I need to use both ui bootstrap and tabbedslidebox in my project but when I am using ui bootstrap then tabbedslidebox doesn't works, any idea..
Thanks in Advance
