### ISSUE TITLE
Initial Tab Change Doesn't Work

### ISSUE THREAD

**Issue by shaulhadar** [saravmajestic/ionic#8]
Hello, great work by the way!

I saw the initial tab is set up on 0 but on the preview, it starts with the middle tab.

Is there any special way to change that so it will show the first tab? or is it a bug or something?

THanks.

**Comment by saravmajestic** [comment]
Hey. Thanks for checking out. You can checkout the demos here: http://ionic-sarav.rhcloud.com/ionic/tabbedSlideBox/. The first sample has attribute 'tabs' set to 2. That is why it shows second tab. Hope it helps you.

**Comment by shaulhadar** [comment]
Thanks man
